export const routes = {
         home: '/',
         brides: '/brides',
         bride: '/brides/:id',
         extras: '/extras',
         extra: '/extras/:id',
         churchs: '/churchs',
         church: '/churchs/:id',
         mlodapara: '/mlodapara/:id',
         pannamloda: '/pannamloda/:id',
         uroczystosc: '/uroczystosc/:id',
         wedding: '/wedding/:id',
         omsvadba: '/omsvadba/:id',
         accesories: '/accesories',
         accesorie: '/accesories/:id',
       };
