export const routes = {
  home: '/',
  brides: '/brides',
  bride: '/brides/:id',
  extras: '/extras',
  extra: '/extras/:id',
  churchs: '/churchs',
  church: '/churchs/:id',
  press: '/presses/:id',
  presses: '/presses',
  accesories: '/accesories',
  accesorie: '/accesories/:id',
  fairs: '/fairs',
  fair: '/fairs/:id',
  travel: '/travels/pleace/:id',
  travels: '/travels',
  dresses: '/dresses',
  dress: 'dresses/:id',  
  dekoracje: '/dekoracje/:id',
  atrakcje: '/atrakcje/:id',
  moda: '/moda/:id',
  zespoly: '/zespoly/:id',
  foto: '/foto/:id',
  lokale: '/lokale/:id',
  pozostale: '/pozostale/:id',
};
